require 'json'
require_relative '../version'

module UDSPlusTestKit
    class ValidateManifestTest < Inferno::Test
        id :uds_plus_validate_manifest_test
        title 'Validate UDS+ Import Manifest'
        description %(
            Test takes the resource generated by the prior test,
            and validates whether the resource conforms to the 
            UDS+ Import Manifest Structure Definition.
        )

        def manifest_scratch
            scratch[:manifest_resources] ||= {}
        end

        def manifest_resources
            manifest_scratch[:all] ||= []
        end

        run do
            profile_definition = "http://hl7.org/fhir/us/uds-plus/StructureDefinition/uds-plus-import-manifest"
            profile_with_version = "#{profile_definition}|#{UDS_PLUS_VERSION}"
            assert_valid_resource(resource: manifest_resources.first, profile_url: profile_with_version)
        end
    end
end
